### PR TITLE
Fixes 7: Allow partial key matching in default loading

### PR DESCRIPTION
**Pull request by thomscode**
Fixes issue #7

### CODE REVIEW

**Comment by thomscode** [comment]
Is there anything I can do to help push this forward? Or is this something you aren't looking for? It ended up being a deal breaker for me as the default values I was setting weren't getting loaded without this patch.

**Comment by greg-1-anderson** [comment]
Sorry for the delay; did not notice this PR earlier.

It seems this would be a lot more efficient if you used `Dflydev\DotAccessData\Data` for $defaults in addition to $data. Would that work for you?

You might also consider using a ConfigOverlay instead of defaults.

**Comment by thomscode** [comment]
Looking back at my project I think my use case for this, has updated to using multiple yaml configuration files. I still think the implementation prior to my patch wasn't correct (my opinion) but as I'm a few versions behind, I'll restart and see how the changes work and whether my patch is necessary or not.

Thanks for the update.

**Comment by greg-1-anderson** [comment]
ConfigOverlay is the designed way to combine multiple configuration files (in instances where you might need to preserve rather than overwrite the lower-priority values as defaults). The default value code is mostly legacy, brought along from the earlier simpler code that this grew out of. We could make the default value handling better, but I'd recommend trying ConfigOverlay first and see if that works better.

**Comment by thomscode** [comment]
Ok that makes sense. I'll close this PR then.

I'm creating a Drupal build tool for my company's Drupal team, and Robo is replacing a legacy task runner script created before I arrived (and sorely outdated). As I started learning Robo I read the documentation and was trying to use the "[default configuration](http://robo.li/getting-started/#providing-default-configuration-in-code)" mentioned there.

Looking at my code now, at some point after writing the patch, I switched to using ConfigOverlay by importing consecutive configuration files in my `RoboFile`'s constructor. I especially like the way you can re-use values with the `${}` syntax (extremely helpful).

Since the default value code is legacy I won't pursue this any further. Do you want me to create a pull request on `consolidation/robo` to update the documentation there? or do you want to handle that since you are more familiar with how the configuration works?

**Comment by greg-1-anderson** [comment]
It would be very helpful if you could submit a documentation PR for Robo. Sounds like you have a good handle on how things are working now. I'll be happy to answer any questions or make any needed corrections.

**Comment by thomscode** [comment]
Done in [consolidation/robo#646](https://github.com/consolidation/Robo/pull/646)

**Pull request closed without merging**
