### PR TITLE
Selective distinct/combine merge strategy.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
In Drush configuration files, it is possible to define additional paths where command files and alias file paths may be found. For example, the following config will make the Drush 9 configuration behavior similar to what Drush 8 does:
```
drush:
  paths:
    include:
      - '${env.home}/.drush/commands'
      - /usr/share/drush/commands
    alias-path:
      - '${env.home}/.drush/sites'
      - /etc/drush/sites
```
A problem arises, though, when there are multiple `drush.yml` files, each with their own `include` &/or `alias-path` configurations, then the current implementation will return the paths from only one of the configuration files. The paths in all of the other configuration files will be overwritten and ignored.

What is needed to fix this limitation is a merge strategy that unions together all of the paths from all of the `drush.yml` files. However, it would not necessarily be appropriate to union all of the arrays from all configuration files.

The preliminary idea in this PR is to provide an API to specify the exact path for config items where array values should be unioned rather than replaced. 

Here is how it would be used in Drush `\Drush\Config\ConfigLocator`:
```
    public function addConfigPaths($contextName, $paths)
    {
        $loader = new YamlConfigLoader();
        // Make all of the config values parsed so far available in evaluations.
        $reference = $this->config()->export();
        $processor = new ConfigProcessor();
        $processor->selectMergeStrategy(['drush.paths.include', 'drush.paths.alias-path']);
```
I'm not sure what the right solution is here, though. If we go with a solution similar to this one, I think I'll switch from an array of strings to a class with an API.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I did consider whether it might be simpler, yet still acceptable to simply always merge rather than replace simple (non-associative) arrays. I'm not sure whether this might have unintended consequences, so it might not be something that could be considered to be a backwards compatible change if we did it that way.

**Comment by weitzman** [comment]
I havent heard much demand for this. Is this another ISP led feature? 

Regardless, it looks OK to me, as far as it goes.

**Comment by greg-1-anderson** [comment]
I discovered it when setting up isp configuration for Drush. I don't need it for the isp configuration per-se, because isps should only need one drush.yml file. Most folks will have zero drush.yml files in an isp context, and usually only one locally. If anyone ever added a commandfile or alias file location in a site-local drush.yml file, though, this would be a huge wtf, so I thought I should fix it while I understood the code path rather than waiting to do it all again later.

**Comment by greg-1-anderson** [comment]
Reference: https://drupal.slack.com/archives/C62H9CWQM/p1533566157000418

**Pull request merged**
