### PR TITLE
Update Config.php for PHP 8.4

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/drush-ops/drush/issues/6069

### CODE REVIEW

**Comment by andypost** [comment]
```
PHP Deprecated:  Consolidation\Config\Config::__construct(): Implicitly marking parameter $data as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/web/vendor/consolidation/config/src/Config.php on line 33

Deprecated: Consolidation\Config\Config::__construct(): Implicitly marking parameter $data as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/web/vendor/consolidation/config/src/Config.php on line 33
```

**Comment by greg-1-anderson** [comment]
I'll make new releases with 8.4 support as soon as the CI config is updated to cover 8.4. Will do that as soon as I'm able; PRs also welcome.

**Comment by andypost** [comment]
@greg-1-anderson CI already can use `8.4` but as I see there's no matrix testing for the package

**Comment by greg-1-anderson** [comment]
@andypost The matrix is not regular / complete, as I didn't want to test both Linux and Windows across all php versions. Currently, only PHP 8.2 is tested on both Linux and Windows; [PHP 8.3 is added in via an "include"](https://github.com/consolidation/config/blob/main/.github/workflows/ci.yml#L99,L104). PHP 8.4 could be another element in this include list.

**Pull request merged**
